#!/bin/bash

DIRNAME=$1

if [ -z "${DIRNAME}" ]; then
    echo "The first parameter to this script must be a directory name"
    exit 1;
fi;

FILENAME="${DIRNAME}/index.html"

cat > $FILENAME <<EOF
<html>
  <head>
    <title>${DIRNAME}</title>
  </head>
  <body>
    <center><h1>${dirname}</h1></center>
    <br/>

    <ul>
EOF


for f in $(find $DIRNAME -maxdepth 1 -type f | sort); do
    FILE=$(basename $f)
    cat >> $FILENAME <<EOF
     <li><a href="${FILE}">${FILE}</a></li>
EOF
done;

cat >> $FILENAME <<EOF

    </ul>
    <br/>
    <center>
        This page generated by
        <a href="https://github.com/jenkins-infra/infra-statistics/blob/master/$(basename $0)">this script</a>
    </center>
  </body>
</html>
EOF
